import {chromium} from 'playwright';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';import {fileURLToPath} from 'node:url';
import {startSite} from './server.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url)),out=path.join(dir,'evidence','diagnostics');await mkdir(out,{recursive:true});
const site=await startSite(),browser=await chromium.launch();const records=[];
async function scenario(id,fn){const context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage();p.setDefaultTimeout(4000);await p.goto(site.url);const result={id};try{Object.assign(result,await fn(p));await p.screenshot({path:path.join(out,id+'.png'),fullPage:true})}catch(e){result.error=e.message}finally{records.push(result);await context.close();}}
const t=(p,s)=>p.locator(s).innerText();const row=(p,id)=>p.locator('#devBody tr').filter({hasText:id});
async function all(p){for(const x of ['stIdle','stBusy','stMaint'])await p.locator('#'+x).check();}
async function book(p,purpose,start='11',end='13') {await p.locator('#batchBook').click();await p.locator('#to2').click();await p.locator('#applicant').fill('赵六');await p.locator('#purpose').fill(purpose);await p.locator('#date').fill('2026-10-10');await p.locator('#start').selectOption(start);await p.locator('#end').selectOption(end);await p.locator('#to3').click();}
await scenario('D01-reset',async p=>{const initial=await t(p,'#pageInfo');await all(p);const allStates=await t(p,'#pageInfo');await p.locator('#sort').selectOption('feeDesc');await p.locator('#resetFilter').click();return{initial,all_states_via_ui:allStates,after_reset:await t(p,'#pageInfo'),sort_after_reset:await p.locator('#sort').inputValue(),empty_visible:await p.locator('#devEmpty').isVisible()}});
await scenario('D02-details-stale',async p=>{await row(p,'EQ-101').getByRole('button',{name:'详情'}).click();await p.locator('#drawerBox').waitFor({state:'visible'});const first=await t(p,'#drawerBox');await p.locator('#drawerClose').click();await p.locator('#q').fill('EQ-106');await row(p,'EQ-106').getByRole('button',{name:'详情'}).click();await p.locator('#drawerBox').waitFor({state:'visible'});return{first_drawer:first,second_title:await t(p,'#drawerTitle'),second_drawer:await t(p,'#drawerBox'),second_basic:await t(p,'#drawerBasic'),second_tab_panel:await t(p,'#tabPanel')}});
await scenario('D03-conflict-valid-purpose',async p=>{await p.locator('#q').fill('EQ-103');await row(p,'EQ-103').locator('input').check();await book(p,'时间冲突复测验证');const overlap=await t(p,'#bookMsg');await p.screenshot({path:path.join(out,'D03-overlap.png'),fullPage:true});await p.locator('#start').selectOption('9');await p.locator('#end').selectOption('10');await p.locator('#to3').click();return{purpose:'时间冲突复测验证',separate_from_original_KC21:true,overlap_error:overlap,boundary_confirmation_visible:await p.locator('#step3').isVisible(),boundary_summary:await t(p,'#confirmBox')}});
await scenario('D04-single-click-multi',async p=>{await row(p,'EQ-101').locator('input').check();await row(p,'EQ-105').locator('input').check();await book(p,'联合压力测试','13','15');const confirm=await t(p,'#confirmBox');await p.locator('#confirmBook').click();return{clicks:1,confirmation:confirm,rows:await p.locator('#recBody tr').allTextContents(),confirmed_count:await t(p,'#statConf'),confirmed_amount:await t(p,'#statFee')}});
await scenario('D05-mobile',async p=>{await p.setViewportSize({width:390,height:844});return{viewport:390,document_width:await p.evaluate(()=>document.documentElement.scrollWidth),table_scroll_width:await p.locator('.tablewrap').first().evaluate(e=>e.scrollWidth),visible_viewport_width:await p.evaluate(()=>innerWidth)}});
await browser.close();await site.close();await writeFile(path.join(out,'results.json'),JSON.stringify({kind:'Codex supplementary diagnosis; not a rerun or repair of Kimi cases',browser_sessions:records.length,records},null,2));console.log(JSON.stringify(records,null,2));
