import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const author=path.resolve(process.argv[2]);
const hash=b=>createHash('sha256').update(b).digest('hex');
const manifest=JSON.parse(await fs.readFile(path.join(root,'../heldout-lab/manifest.json')));
for(const f of manifest.files)if(hash(await fs.readFile(path.join(root,'../heldout-lab',f.path)))!==f.sha256)throw Error('FROZEN_INPUT_MISMATCH:'+f.path);
const original=JSON.parse(await fs.readFile(path.join(root,'../heldout-lab/cases.json'))).cases.find(c=>c.case_id==='HOLD-S1');
const input=JSON.stringify(original,null,2)+'\n';
await fs.mkdir(path.join(root,'private'),{recursive:true});
await fs.writeFile(path.join(author,'normal-case.json'),input);
const official=await fs.readFile(path.join(root,'.claude/agents/playwright-test-generator.md'),'utf8');
const generator=official.replace(/^---[\s\S]*?---\s*/, '');
const prompt=`Use the official Playwright Test Generator instructions below to generate ONE test from the supplied original normal case. Do not invent scenarios or business expectations. You have only a gated subset of official Playwright tools. No file reading, shell, arbitrary evaluate, other pages, or healer. Tool unavailability must be reported, not worked around.\n${generator}\n\nOriginal case (unchanged source of truth):\n${input}\nEnvironment: seedFile MUST be seed.spec.ts; output MUST be tests/sorting.spec.ts. Run generator_setup_page once with the original case as plan, then perform each original action and verify expected UI live, read generator log and write the test once. The seed already opens the allowed entry. Preserve every original obligation, all literal text, exact positions, units and timing. S02 unchanged table means capture the ENTIRE visible table content before selecting, then compare after selection, not only IDs/powers. For final reusable test navigate using process.env.PILOT_ENTRY_URL || the original normal URL; no other branch, no retries/skip/fixme/expected-failure. Use test.step named S01..S04, explicit assertions and original source comments. Do NOT execute generated code via tools; the coordinator audits it first. Final answer in Chinese: obligation-to-assertion mapping and unsupported items. Stop after writing one draft. Never assert that human approval or official regression happened.`;
await fs.writeFile(path.join(author,'generation-prompt.txt'),prompt);
const cli=path.join(root,'node_modules/playwright/cli.js');
const mcp={mcpServers:{'playwright-test':{command:process.execPath,args:[path.join(root,'mcp-gate.mjs'),author,cli,original.page_entry_url,path.join(root,'private/draft-1-tools.jsonl')]}}};
await fs.writeFile(path.join(author,'mcp.local.json'),JSON.stringify(mcp,null,2));
const freeze={base_commit:'c1e9455d6cb32fd919b604585ba440c4997448ee',group:'sorting',allowed_entry:original.page_entry_url,input_sha256:hash(input),official_generator_sha256:hash(official),playwright:'1.62.1',claude_code:'2.1.218',configured_provider:'https://api.deepseek.com/anthropic',configured_model:'deepseek-v4-pro',authoring_rounds:{draft:1,max_corrections:2,max_tool_calls_per_round:100,max_minutes_per_round:20},regression:{normal:3,fault:3,retries:0,model_calls:0,requires_human_approval:true},prepared_at:new Date().toISOString(),authoring_directory:author,script_frozen:false,human_approved:false};
await fs.writeFile(path.join(root,'private/input-freeze.json'),JSON.stringify(freeze,null,2));
console.log(JSON.stringify({input_sha256:freeze.input_sha256,official_generator_sha256:freeze.official_generator_sha256,authoring_directory:author}));
