import fs from 'node:fs/promises';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const [author,claudeExe,round='draft-1']=process.argv.slice(2);
if(!['draft-1','correction-1','correction-2'].includes(round))throw Error('ROUND_DENIED');
if(round!=='draft-1')await fs.access(path.join(root,'private',round==='correction-1'?'draft-1-result.json':'correction-1-result.json'));
const journal=path.join(root,'private',round+'-session.jsonl');
try{await fs.access(journal);throw Error('DRAFT_ALREADY_ATTEMPTED');}catch(e){if(e.code!=='ENOENT')throw e;}
const settings=JSON.parse(await fs.readFile(path.join(process.env.USERPROFILE,'.claude/settings.json'),'utf8'));
if(settings.env?.ANTHROPIC_MODEL!=='deepseek-v4-pro'||settings.env?.ANTHROPIC_BASE_URL!=='https://api.deepseek.com/anthropic')throw Error('CONFIG_CHANGED');
const env={...process.env,...settings.env,CLAUDE_CONFIG_DIR:path.join(author,'isolated-claude-config'),CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC:'1',CLAUDE_CODE_DISABLE_AUTO_MEMORY:'1'};
delete env.CLAUDECODE;
if(!env.ANTHROPIC_API_KEY && env.ANTHROPIC_AUTH_TOKEN)env.ANTHROPIC_API_KEY=env.ANTHROPIC_AUTH_TOKEN;
let prompt=await fs.readFile(path.join(author,'generation-prompt.txt'),'utf8');
if(round==='correction-1')prompt+='\nCorrection round: prior attempt stopped before business steps due to seed/project mismatch. The owned seed is now selected by the gateway; seedFile=seed.spec.ts and project=chromium, or omit them. This is the same original normal case. No new business facts or expected results were added.';
if(round==='correction-2')prompt+='\n'+await fs.readFile(path.join(root,'correction-2-feedback.md'),'utf8')+'\nYour own preceding normal draft:\n'+await fs.readFile(path.join(author,'tests/sorting.spec.ts'),'utf8');
const mcp=JSON.parse(await fs.readFile(path.join(author,'mcp.local.json')));
mcp.mcpServers['playwright-test'].args[4]=path.join(root,'private',round+'-tools.jsonl');
const mcpPath=path.join(author,round+'-mcp.local.json');
await fs.writeFile(mcpPath,JSON.stringify(mcp,null,2));
const args=['--bare','--print','--verbose','--output-format','stream-json','--no-session-persistence','--disable-slash-commands','--no-chrome','--setting-sources','project','--strict-mcp-config','--mcp-config',mcpPath,'--tools','','--allowedTools','mcp__playwright-test__*','--permission-mode','dontAsk','--model','deepseek-v4-pro'];
const started=Date.now();await fs.writeFile(journal,'');
const out=await fs.open(journal,'a'),err=await fs.open(path.join(root,'private',round+'.stderr.log'),'a');
const child=spawn(claudeExe,args,{cwd:author,env,stdio:['pipe',out.fd,err.fd],windowsHide:true});
child.stdin.end(prompt);
await fs.writeFile(path.join(root,'private',round+'-launch.json'),JSON.stringify({started_at:new Date(started).toISOString(),pid:child.pid,model:'deepseek-v4-pro',prompt_sha256:createHash('sha256').update(prompt).digest('hex'),flags:args,deadline:new Date(started+1200000).toISOString()},null,2));
console.log(JSON.stringify({pid:child.pid,started_at:new Date(started).toISOString()}));
let timedOut=false;const timer=setTimeout(()=>{timedOut=true;child.kill();},1200000);
const code=await new Promise(resolve=>{child.once('exit',resolve);child.once('error',()=>resolve(-1));});
clearTimeout(timer);await out.close();await err.close();
const result={exit_code:code,timed_out:timedOut,elapsed_ms:Date.now()-started,finished_at:new Date().toISOString(),human_approved:false,formal_regression_executed:false};
await fs.writeFile(path.join(root,'private',round+'-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
process.exitCode=code??1;
