import { api } from './api.js';
import { esc, stateLabel } from './workflow.js';

// Compatibility inside the same product shell. Project-bound work returns to its case.
export async function renderHistory({query,showPage,go}) {
  const [{assets},{runs},{tasks}]=await Promise.all([api('/api/assets'),api('/api/runs'),api('/api/build/tasks')]);
  const runId=query.get('run_id'),taskId=query.get('task_id');
  const run=runId?runs.find(r=>r.run_id===runId):null,task=taskId?tasks.find(t=>t.task_id===taskId):null;
  if(runId&&!run||taskId&&!task)throw Error('指定历史对象不存在');
  const source=task?.source||null;
  if(source?.project_id&&source.case_id)return go(`#/projects/${encodeURIComponent(source.project_id)}/build-tasks/${encodeURIComponent(taskId)}`,true);
  if(run?.project_id&&run.executed_case_id)return go(`#/projects/${encodeURIComponent(run.project_id)}/cases/${encodeURIComponent(run.executed_case_id)}?version=${run.executed_case_version}&run_id=${encodeURIComponent(runId)}`,true);
  const chosen=run||task,files=chosen?.files||[],mediaBase=run?`/api/runs/${encodeURIComponent(runId)}`:`/api/build/tasks/${encodeURIComponent(taskId)}`;
  const links=files.filter(f=>run||f.web_visible).map(f=>`<p><a href="${mediaBase}/${run||/video|screenshot|trace/.test(f.kind)?'media':'files'}/${encodeURIComponent(f.file_id)}" target="_blank" rel="noreferrer">${esc(f.file_name||f.relative_path)}</a> · SHA ${esc(f.sha256||'未登记')}</p>`).join('');
  showPage(`<div class="page-heading"><div><h1>历史记录与批准资产</h1><p>保留早期未绑定项目的记录与证据；项目内测试从用例库进入。</p></div><a data-nav href="#/projects">返回项目</a></div>${chosen?`<section class="panel"><div class="panel-body"><h2>${esc(task?.template?.title||run?.asset_id||'历史运行')}</h2><p>${esc(chosen.task_status||chosen.execution_status)} · ${esc(chosen.status||chosen.verification_status||'')}</p><details><summary>原始记录与核查依据</summary><pre>${esc(JSON.stringify(chosen,null,2))}</pre></details><h3>登记证据</h3>${links||'<p>此记录未登记可读证据。</p>'}${run&&['QUEUED','RUNNING','STOPPING'].includes(run.execution_status)?'<button class="button" id="history-stop">停止本次运行</button>':''}</div></section>`:''}<section class="panel"><div class="panel-body"><h2>已批准资产</h2>${assets.map((a,n)=>`<article><h3>${esc(a.title)}</h3><p>${esc(a.version)} · ${esc(a.approval_status)} · ${esc(a.script?.sha256)}</p><label>登记环境<select data-asset-env="${n}">${(a.allowed_environments||[]).map(e=>`<option value="${esc(e.id)}">${esc(e.label||e.id)}</option>`).join('')}</select></label><button class="button" data-asset-run="${n}">运行已有批准脚本（不调用模型）</button></article>`).join('')||'<p>当前数据配置没有批准资产。</p>'}<p role="alert" id="history-message"></p></div></section><section class="panel"><div class="panel-body"><h2>历史运行</h2>${runs.map(r=>`<p><a data-nav href="#/history?run_id=${encodeURIComponent(r.run_id)}">${esc(r.started_at||r.created_at)} · ${esc(r.executed_external_id||r.asset_id||r.run_id)} · ${esc(stateLabel(r.status)||stateLabel(r.execution_status))}</a></p>`).join('')||'<p>暂无历史运行。</p>'}<h2>历史开发记录</h2>${tasks.map(t=>`<p><a data-nav href="#/history?task_id=${encodeURIComponent(t.task_id)}">${esc(t.created_at)} · ${esc(t.source?.external_id||t.template?.title||'开发任务')} · ${esc(t.task_status)}</a></p>`).join('')||'<p>暂无历史开发记录。</p>'}</div></section>`);
  const post=body=>({method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
  document.querySelectorAll('[data-asset-run]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{const n=Number(button.dataset.assetRun),r=await api('/api/runs',post({asset_id:assets[n].asset_id,environment:document.querySelector(`[data-asset-env="${n}"]`).value}));go(`#/history?run_id=${encodeURIComponent(r.run_id)}`);}catch(e){document.querySelector('#history-message').textContent=e.message;button.disabled=false;}});
  document.querySelector('#history-stop')?.addEventListener('click',async e=>{e.target.disabled=true;await api(`/api/runs/${encodeURIComponent(runId)}/stop`,post({}));});
}
