import { api } from './api.js';
import { esc, stateLabel } from './workflow.js';
export async function renderReports({project,query,showPage,go}){
  const base=`/api/case-library/projects/${project.project_id}/reports`,id=query.get('report_id');
  if(id){
    const r=await api(`${base}/${encodeURIComponent(id)}`);
    showPage(`<div class="page-heading"><div><h1>测试报告预览</h1><p>固定${r.scope==='batch'?'测试批次':'用例运行'} · ${esc(r.batch_id||r.run_id)} · ${esc(r.created_at)}</p></div><a class="button primary" href="${base}/${r.report_id}/html?download=1" download>下载离线 HTML 报告</a></div><p class="notice">这是已保存快照；后续复测不更新此报告。请求 ${r.counts.requested} 条，未执行 ${r.counts.not_run} 条；未携带的媒体会在报告中明确列出。</p><a data-nav href="#/projects/${project.project_id}/reports">返回报告列表</a><iframe class="report-preview" title="固定范围报告预览" src="${base}/${r.report_id}/html"></iframe>`);return;
  }
  const [saved,{batches},{records}]=await Promise.all([api(base),api(`/api/case-library/projects/${project.project_id}/batches`),api(`/api/case-library/projects/${project.project_id}/execution-records`)]);
  const runId=query.get('run_id'),batchId=query.get('batch_id');
  if(runId&&!records.some(r=>r.run_id===runId)||batchId&&!batches.some(b=>b.batch_id===batchId))throw Error('指定报告对象不属于当前项目');
  showPage(`<div class="page-heading"><div><h1>报告</h1><p>指定批次或单用例的指定运行；与用例包导出分别管理。</p></div></div><div class="report-layout"><section class="panel"><div class="panel-body"><h2>创建固定范围报告</h2><label class="field">报告范围<select id="report-scope"><option value="batch">指定测试批次</option><option value="run" ${runId?'selected':''}>单用例指定运行</option></select></label><label class="field">测试批次<select id="report-batch"><option value="">请选择</option>${batches.filter(b=>['FINISHED','CANCELLED','INTERRUPTED'].includes(b.state)).map(b=>`<option value="${b.batch_id}" ${batchId===b.batch_id?'selected':''}>${esc(b.created_at)} · ${esc(b.software_version||'版本未提供')} · ${b.items.length} 条 · ${esc(stateLabel(b.state))}</option>`).join('')}</select></label><label class="field">具体运行<select id="report-run"><option value="">请选择</option>${records.map(r=>`<option value="${esc(r.run_id)}" ${runId===r.run_id?'selected':''}>${esc(r.executed_external_id)} v${r.executed_case_version} · ${esc(r.started_at)} · ${esc(r.status)}</option>`).join('')}</select></label><p>截图默认内嵌；可选择原始录像、中文回放和 Trace。附件合计上限 80 MB；超限或缺失项明确标记，不输出本机链接冒充离线附件。</p><label><input type="checkbox" id="report-video">携带视频（可能较大）</label><label><input type="checkbox" id="report-trace">携带 Trace（请确认无敏感业务资料）</label><p id="report-message" role="status"></p><button class="button primary" id="report-create">生成快照并预览</button><button class="button" id="report-cancel" hidden>取消生成</button></div></section><section class="panel"><div class="panel-body"><h2>已保存报告</h2>${saved.reports.map(r=>`<p><a data-nav href="#/projects/${project.project_id}/reports?report_id=${r.report_id}">${esc(r.created_at)} · ${r.scope==='batch'?'测试批次':'单用例运行'} · ${r.entry_count} 条</a></p>`).join('')||'<p>尚无报告快照</p>'}</div></section></div>`);
  const toggle=()=>{const single=document.querySelector('#report-scope').value==='run';document.querySelector('#report-batch').closest('label').hidden=single;document.querySelector('#report-run').closest('label').hidden=!single;};toggle();document.querySelector('#report-scope').onchange=toggle;
  let sending=false;const requestId='report-'+crypto.randomUUID();
  document.querySelector('#report-cancel').onclick=async e=>{e.target.disabled=true;try{const r=await api(base+'/cancel',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({request_id:requestId})});document.querySelector('#report-message').textContent=r.state==='FINISHED'?'快照已先完成，保留已生成结果。':'已请求取消，等待服务端确认。';}catch(err){document.querySelector('#report-message').textContent=err.message;}};
  document.querySelector('#report-create').onclick=async e=>{if(sending)return;sending=true;e.target.disabled=true;document.querySelector('#report-cancel').hidden=false;document.querySelector('#report-cancel').disabled=false;const scope=document.querySelector('#report-scope').value;try{const payload={scope,request_id:requestId,include_video:document.querySelector('#report-video').checked,include_trace:document.querySelector('#report-trace').checked};payload[scope==='batch'?'batch_id':'run_id']=document.querySelector(scope==='batch'?'#report-batch':'#report-run').value;if(!payload[scope==='batch'?'batch_id':'run_id'])throw Error('请先选择固定报告范围');document.querySelector('#report-message').textContent='正在核对证据并保存快照…';const r=await api(base,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});go(`#/projects/${project.project_id}/reports?report_id=${r.report_id}`);}catch(err){document.querySelector('#report-message').textContent=err.message==='REPORT_CANCELLED'?'已取消生成，未保存新快照。':err.message;sending=false;e.target.disabled=false;document.querySelector('#report-cancel').hidden=true;}};
}
