export const stateLabel=s=>({PREVIEW:'准备检查',QUEUED:'排队中',RUNNING:'执行中',STOPPING:'取消中',FINISHED:'执行结束',CANCELLED:'已取消',INTERRUPTED:'服务中断',NOT_RUN:'未执行',BLOCKED:'阻塞',PASSED:'通过',FAILED:'失败'}[s]||s);
export const reviewLabels={REVIEWED_COMPLETE_FOR_THIS_CASE:'本次核查完整（未批准）',NOT_ACCEPTED_ACTION_CHANGED:'动作/预期偏离，不采纳',REVIEW_REQUIRED_PRECONDITION_ADDED:'前置条件待确认',BUSINESS_DIFFERENCE_RETAINED:'业务差异保留，待核对',BUSINESS_DIFFERENCE_WITH_COVERAGE_GAP:'覆盖不足，业务差异保留',FROZEN_CASE_INPUT_CONFLICT:'原用例输入矛盾，待澄清'};
export const batchReasons={SCRIPT_MISSING:'缺少脚本',CASE_VERSION_NOT_APPLICABLE:'脚本不适用于此用例版本',SCRIPT_SELECTION_REQUIRED:'存在多个脚本，请在详情明确选择',REQUIREMENTS_REJECTED_DIAGNOSTIC_ONLY:'核查不采纳，仅允许明确诊断试跑',TRIAL_NOT_AUTHORIZED:'没有此版本的技术试跑授权',TRIAL_ENVIRONMENT_UNAVAILABLE:'环境未就绪',TRIAL_BUNDLE_MISSING:'文件包缺失',BATCH_CANCELLED:'取消后未执行',SERVICE_INTERRUPTED_NO_REPLAY:'服务中断，不自动重放'};
export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function reviewHtml(review){return `<div class="notice ${review?.requirements_status==='REVIEWED_COMPLETE_FOR_THIS_CASE'?'':'warning'}" data-testid="requirement-review"><strong>要求核查：${esc(reviewLabels[review?.requirements_status]||'待核对')}</strong><p>${esc(review?.finding||'尚无绑定此用例版本和文件包的维护者核查；运行通过不代表要求完整。')}</p>${review?`<details><summary>核查来源（不等于正式批准）</summary><pre>${esc(JSON.stringify(review,null,2))}</pre></details>`:''}</div>`;}
export function batchHtml(b,base){const count=s=>b.items.filter(i=>i.state===s).length;return `<article data-batch-id="${esc(b.batch_id)}"><h3>测试批次 · ${esc(b.created_at)}</h3><p>范围：${esc({single:'单条',selected:'选中列表',project:'整个项目（含阻塞项）'}[b.scope])} · 软件版本：${esc(b.software_version||'未提供')} · 状态：${esc(stateLabel(b.state))} · ${b.mode==='diagnostic'?'诊断试跑':'限定技术试跑'}，未批准</p><p>请求 ${b.items.length} 条；已执行 ${count('FINISHED')+count('CANCELLED')}；阻塞 ${count('BLOCKED')}；未执行 ${count('NOT_RUN')+count('QUEUED')}。结果只属于本批。</p><table><thead><tr><th>用例</th><th>版本 / 脚本</th><th>本次状态</th><th>原因</th></tr></thead><tbody>${b.items.map(i=>`<tr><td><a data-nav href="${base}/cases/${encodeURIComponent(i.case_id)}?version=${i.case_version}&batch_id=${b.batch_id}${i.run_id?'&run_id='+encodeURIComponent(i.run_id):''}">${esc(i.external_id)} · ${esc(i.title)}</a></td><td>用例v${i.case_version} / ${i.selection?'候选v'+i.selection.candidate_version:'无'}</td><td>${esc(stateLabel(i.state))} · ${esc(stateLabel(i.result)||'未执行')}</td><td>${esc(batchReasons[i.reason]||i.reason||'—')}</td></tr>`).join('')}</tbody></table><details><summary>技术详情：冻结清单及身份</summary><pre>${esc(JSON.stringify(b,null,2))}</pre></details></article>`;}
export async function openBatch({project,scope,ids,selections=[],api,mutate,jsonOptions,go,toast,caseContext}){
 const root=document.querySelector('#modal-root');let preview=null,starting=false;const requestId='batch-request-'+crypto.randomUUID();
 root.innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-label="已有脚本技术复跑"><h2>已有脚本技术复跑 · 不调用模型</h2><p>范围：${scope==='project'?`整个项目 ${project.cases.length} 条（不受筛选或分页影响）`:ids.length+' 条'}。不修改脚本，不自动批准。</p><label>被测软件版本 / 构建标识<input id="batch-software" placeholder="未提供"></label><label><input type="checkbox" id="batch-diagnostic">明确诊断试跑（可包含核查不采纳的候选，不属于正式回归）</label><div id="batch-preview"></div><p id="batch-error" role="alert"></p><div class="actions"><button class="button" id="batch-preflight">检查准备条件</button><button class="button primary" id="batch-start" disabled>确认运行已有脚本</button><button class="button" id="batch-close">关闭</button></div></section></div>`;
 const reset=()=>{preview=null;document.querySelector('#batch-start').disabled=true;document.querySelector('#batch-preview').innerHTML='条件已改变，请重新检查。';};
 document.querySelector('#batch-software').addEventListener('input',reset);document.querySelector('#batch-diagnostic').addEventListener('change',reset);
 document.querySelector('#batch-close').onclick=()=>{if(!starting)root.innerHTML='';};
 document.querySelector('#batch-preflight').onclick=async e=>{e.target.disabled=true;try{preview=await mutate(`/api/case-library/projects/${project.project_id}/batches`,jsonOptions({scope,case_ids:ids,selections,software_version:document.querySelector('#batch-software').value,mode:document.querySelector('#batch-diagnostic').checked?'diagnostic':'technical'}));document.querySelector('#batch-preview').innerHTML=`<p>请求 ${preview.items.length} 条，可运行 ${preview.items.filter(i=>i.state==='QUEUED').length} 条，待处理 ${preview.items.filter(i=>i.state==='BLOCKED').length} 条。</p><ul>${preview.items.map(i=>`<li>${esc(i.external_id)}：${esc(batchReasons[i.reason]||i.reason||'限定技术试跑（未批准）')}；要求核查：${esc(reviewLabels[i.requirement_review?.requirements_status]||'待核对')}</li>`).join('')}</ul>${preview.items.some(i=>i.state==='BLOCKED')?'<label><input id="batch-partial" type="checkbox">明确仅运行可执行部分，保留全部阻塞项</label>':''}`;document.querySelector('#batch-start').disabled=!preview.items.some(i=>i.state==='QUEUED');}catch(err){document.querySelector('#batch-error').textContent=err.message;}finally{e.target.disabled=false;}};
 document.querySelector('#batch-start').onclick=async e=>{if(starting||!preview)return;starting=true;e.target.disabled=true;try{const b=await mutate(`/api/case-library/projects/${project.project_id}/batches/${preview.batch_id}/start`,jsonOptions({request_id:requestId,allow_partial:document.querySelector('#batch-partial')?.checked===true}));root.innerHTML='';go(caseContext?`#/projects/${project.project_id}/cases/${caseContext.case_id}?version=${caseContext.case_version}&batch_id=${b.batch_id}`:`#/projects/${project.project_id}/batches?batch_id=${b.batch_id}`,true);}catch(err){document.querySelector('#batch-error').textContent=err.message;starting=false;e.target.disabled=false;}};
}
